language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="spelll:."
  - DISTRO="ubuntu-16.04"
  matrix:
  - PACKAGE="spelll" OCAML_VERSION="4.02.3" TESTS=false
  - PACKAGE="spelll" OCAML_VERSION="4.03"
    #- PACKAGE="spelll" OCAML_VERSION="4.04"
    #- PACKAGE="spelll" OCAML_VERSION="4.05" EXTRA_DEPS="base-bigarray"
  - PACKAGE="spelll" OCAML_VERSION="4.06"
  - PACKAGE="spelll" OCAML_VERSION="4.07"
